DROP TABLE Users,Documente,Cereri,Locuinte;
CREATE TABLE IF NOT EXISTS Users(ID_column VARCHAR(50) NOT NULL PRIMARY KEY,
		  TIP_USER_COLUMN VARCHAR(50) NOT NULL,
		  USERNAME_column VARCHAR(50) NOT NULL,
		  PASSWORD_column VARCHAR(50) NOT NULL,
		  NUME_column VARCHAR(50) NOT NULL,
		  PRENUME_column VARCHAR(50) NOT NULL,
		  UNIQUE(ID_column));

CREATE TABLE IF NOT EXISTS Documente(ID_DOC_column VARCHAR(50) NOT NULL PRIMARY KEY,
		  TIP_column VARCHAR(50) NOT NULL,
		  UNIQUE(TIP_column));

CREATE TABLE IF NOT EXISTS Cereri(ID_column BIGSERIAL NOT NULL PRIMARY KEY,
  		  USER_ID_column VARCHAR(50) NOT NULL REFERENCES Users(ID_column),
		  TIP_CERERE_column VARCHAR(50) NOT NULL REFERENCES Documente(TIP_column),
		  DATA_column VARCHAR(50) NOT NULL,
		  NUME_column VARCHAR(50) NOT NULL,
		  PRENUME_column VARCHAR(50) NOT NULL,
		  ADRESA_column VARCHAR(50) NOT NULL,
		  NUMAR_CERERI_column INT NOT NULL,
		  APROBARE_column VARCHAR(50) NOT NULL);

CREATE TABLE IF NOT EXISTS Locuinte(ID_LOCUINTA_column VARCHAR(50) NOT NULL PRIMARY KEY,
			ID_PROPIETAR_column VARCHAR(50) NOT NULL REFERENCES Users(ID_column),
			NUME_PROPIETAR_column VARCHAR(50) NOT NULL,
			PRENUME_PROPIETAR_column VARCHAR(50) NOT NULL,
			ADRESA_column VARCHAR(50) NOT NULL);

INSERT INTO Users VALUES ('admin','admin','adminuser','adminpass','Dumitrescu','Andrei');
